export const MQTT_TOPIC = {
  RELOAD_ROOM: 'RELOAD_ROOM',
  GET_USER_IN_ROOM: 'GET_USER_IN_ROOM',
  USER_JOIN: 'USER_JOIN',
  USER_RECEIVING_RETURNED_SIGNAL: 'USER_RECEIVING_RETURNED_SIGNAL',
  USER_SENDING_SIGNAL: 'USER_SENDING_SIGNAL',
  USER_RETURNING_SIGNAL: 'USER_RETURNING_SIGNAL',
  SEND_DRAWING: 'USER_SEND_DRAWING',
  RECEIVE_DRAWING: 'USER_RECEIVE_DRAWING'
};
export interface MQTTMessage {
  type: string,
  payload: any
}